### ISSUE TITLE
Is your code suit for EuRoC datasets?

### ISSUE THREAD

**Issue by edgar-explorer** [pauvsi/pauvsi_vio#8]
Thank you for your excellent code. Is your code suit for EuRoC datasets?

**Comment by k-sheridan** [comment]
The code on the master branch right now has no inertial fusion and requires initialization with a flat surface. Even if there was an easy way to test it with the euroc datasets, it would likely fail.

On this branch: https://github.com/Trexter/invio/tree/hybrid_method

I have been implementing a new method which does fuse the IMU measurements allowing to be initialized on the fly while running nearly as fast as the method on the master branch. This branch includes this file: https://github.com/Trexter/invio/blob/hybrid_method/src/euroc_dataset_node.cpp which adds the necessary information the the euroc bag files. Using that lets me test with the euroc dataset. 

The hybrid method branch is not in a working state yet which is why I have not merged it with master yet. If you want to try out the euroc mav datasets with the master branch you will need to use that node with this launch file: https://github.com/Trexter/invio/blob/hybrid_method/launch/euroc_mav.launch
